### ISSUE TITLE
Update to mongodb ~2.0

### ISSUE THREAD

**Issue by dypsilon** [Marsup/hapi-mongodb#12]

**Comment by simon-p-r** [comment]
:+1:

**Comment by Marsup** [comment]
My previous comment still stands.

**Comment by simon-p-r** [comment]
Is it still not stable enough?

**Comment by Marsup** [comment]
Honestly I don't know, but if it's not by its author, it's not by me either.

**Comment by simon-p-r** [comment]
Ok I will find out

**Comment by simon-p-r** [comment]
Open to a PR on this? Version 2 has been announced as stable.

https://www.mongodb.com/blog/post/introducing-nodejs-mongodb-20-driver?utm_source=nodeweekly&utm_medium=email

**Comment by Marsup** [comment]
I'll take care of that immediately.

**Comment by simon-p-r** [comment]
Ok no problem.  Do you find this still the best way to hook databases to hapi?  I recently saw somewhere an example of someone binding to the server object.

**Comment by Marsup** [comment]
Published. I continue using it because it gets configured with my server, but I see that people trying to build models with it (I don't) are not that comfortable. What's the other solution ?

**Comment by simon-p-r** [comment]
No good ones unfortunately!  I currently use your plugin for testing at the moment as the main code base I manage uses a separate mechanisms to connect to mongodb, load schemas (JSON schema), create collection objects (cache them for use in handlers) and create indexes. 

How do you create indexes on your collections?  Would you be open to this plugin having option to control building indexes via a switch and the possibility of creating collection handles to store in hapi's server.app object.  I have looked at server.decorate to achieve this however you cannot manipulate the app object via that method.

**Comment by Marsup** [comment]
I'm open to anything that allows post-initialization code.
