### ISSUE TITLE
Ability to access other types from database besides ObjectID

### ISSUE THREAD

**Issue by mattymcgee** [Marsup/hapi-mongodb#17]
Does this plugin have the ability to access types like string, int, etc from mongodb? In your example you show the retrieval of elements in your database based on ObjectID, but lets say I was trying to search for a specific string in my database and query all the elements connected to that string, like so:

```javascript
server.route({
	method: 'GET',
	path: '/test/cuisines/{cuisine}',
	handler: function(request, reply) {
		var db = request.server.plugins['hapi-mongodb'].db;
		var result = request.server.plugins['hapi-mongodb'].String;

		db.collection('restaurants').findOne({"cuisine": new result(request.params.cuisine)}, function(err, result) {
			if(err) {
				return reply(Boom.internal('Internal MongoDB error', err)); 
			}
			reply(result);
		});
	}
});
```

**Comment by Marsup** [comment]
This doesn't really make sense in the nodejs/mongodb world, types are AFAIK never used. You should have a look at the mongodb module to know how to query mongodb which is far more detailed on the actual db stuff, this is just a plugin that exposes this module.
