### ISSUE TITLE
server.decorate?

### ISSUE THREAD

**Issue by jgallen23** [Marsup/hapi-mongodb#20]
It would be nice to just be able to type `server.db` (or `server.mongodb`) instead of `server.plugins['hapi-mongodb'].db;`.  It seems like plugins like [chairo](https://github.com/hapijs/chairo) are doing that vs expose.

**Comment by Marsup** [comment]
What do you think of decorating the request as well ?

**Comment by Marsup** [comment]
Are you OK with the changes ?

**Comment by jgallen23** [comment]
this is great!  thanks for the quick change

**Comment by Marsup** [comment]
Published.
