### ISSUE TITLE
getting error while doing the npm install for hapi-mongodb

### ISSUE THREAD

**Issue by asifaryan** [Marsup/hapi-mongodb#22]
npm WARN package.json hapi-mongo-api@1.0.0 No repository field.
npm ERR! registry error parsing json
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\nodejs\\\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! Unexpected token <
npm ERR! <html>
npm ERR!   <head>
npm ERR!     <title>404 - Path /hapi-mongodb not found in group repository &quot;npm&quot; [id=npm].</title>
npm ERR!     <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
npm ERR!
npm ERR!     <link rel="icon" type="image/png" href="http://repo.aedc.extra.aexp.com/nexus/favicon.png">
npm ERR!     
npm ERR!
npm ERR!     <link rel="stylesheet" href="http://repo.aedc.extra.aexp.com/nexus/static/css/Sonatype-content.css?2.11.1-01" type="text/css" media="screen" title="no title" charset="utf-8
">
npm ERR!   </head>
npm ERR!   <body>
npm ERR!     <h1>404 - Path /hapi-mongodb not found in group repository &quot;npm&quot; [id=npm].</h1>
npm ERR!     <p>Path /hapi-mongodb not found in group repository &quot;npm&quot; [id=npm].</p>
npm ERR!   </body>
npm ERR! </html>
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\hapi-mongo-api-master\npm-debug.log

**Comment by Marsup** [comment]
Works for me. Are you using some weird custom npm repository ?

**Comment by Marsup** [comment]
Also be aware that as you are using a quite old version of node, you will be stuck on versions 3.x of this module.

**Comment by asifaryan** [comment]
No problem , my npm config file got corrupted. Issue resolved.
