### ISSUE TITLE
db.collection is undefined

### ISSUE THREAD

**Issue by Kadajett** [Marsup/hapi-mongodb#24]
when using the db object, I get `collection` as undefined. 

I am loading the plugin with Glue as well, if that matters. 

At that point, the db objects value is...

```
EventEmitter {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  s: 
   { databaseName: 'DBName.REDACTED',
     dbCache: {},
     children: [],
     topology: 
      EventEmitter {
        domain: null,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        s: [Object],
        bson: [Getter],
        isMasterDoc: [Getter],
        poolSize: [Getter],
        autoReconnect: [Getter],
        host: [Getter],
        port: [Getter],
        emitOpen: false,
        connectTimeoutMS: 30000,
        socketTimeoutMS: 0 },
     options: 
      { read_preference_tags: null,
        readPreference: [Object],
        native_parser: false,
        url: 'mongo://MONGO_URL.Redacted',
        promiseLibrary: [Function: Promise] },
     logger: { className: 'Db' },
     bson: {},
     authSource: undefined,
     readPreference: { _type: 'ReadPreference', mode: 'primary', tags: undefined },
     bufferMaxEntries: -1,
     parentDb: null,
     pkFactory: undefined,
     nativeParser: false,
     promiseLibrary: [Function: Promise],
     noListener: false,
     readConcern: undefined },
  serverConfig: [Getter],
  bufferMaxEntries: [Getter],
  databaseName: [Getter],
  options: [Getter],
  native_parser: [Getter],
  slaveOk: [Getter],
  writeConcern: [Getter] }
```

**Comment by Marsup** [comment]
Looks normal to me. The collection is in the prototype so it won't appear in what you pasted. Can you provide a way to reproduce ?

**Comment by Marsup** [comment]
Also which versions are you using ? (node, hapi, glue, mongodb, hapi-mongodb, ...)

**Comment by kgilski** [comment]
In my case, I had to use db.db(<db_name>) in order to make it work

var MongoClient = require('mongodb').MongoClient;
var url = "mongodb://localhost:27017/mydb";

MongoClient.connect(url, function(err, db) {
  if (err) throw err;

  var dbase = db.db("mydb") // <- HERE

  dbase.createCollection("customers", function(err, res) {
    if (err) throw err;
    console.log("Collection created!");
    db.close();
  });
});

**Comment by cocolote** [comment]
@kgilski Thank you for your comment. Your solution worked for me. This issue is being bothering me for days.
