### ISSUE TITLE
Mongodb Native Driver 2.1.20 issues

### ISSUE THREAD

**Issue by moogway** [Marsup/hapi-mongodb#25]
Hi, this is more a discussion than an issue.

I am using Mongodb 3.0.12 (wiredTiger), nodeJS 6.x, for my fairly large hapi application, running on Ubuntu 14.04.

The native driver bundled with hapi-mongodb right now is 2.1.20 but it has some breaking changes. We found that after some time, a particular database (we have 3-4 mongo databases deployed on a large machine, all running on port 27017, with different urls) stops responding to queries without throwing any sort of error.

So we downgraded the nodejs-mongodb driver to the last known working version 2.1.4 (used in the dev environment) and thankfully mongo started throwing ```MongoError: topology was destroyed```. So we changed the plugin options, while registering, to define values of ```keepAlive``` and ```connectTimeoutMS``` in ```socketOptions```. That seemed to work for now. (In case someone else has the same issue).

The point of all of this is to understand that even though it's a driver issue, shouldn't we bundle hapi-mongodb with a working version of the native mongo driver, instead of version 2.x.x?

Is there anyone else who encountered the same issue?

**Comment by Marsup** [comment]
Well, considering this module requires `"mongodb": "2.x.x"`, if you were to put any 2.x version in your own npm dependencies, npm would deduplicate that and take yours, so I'd say it's not really an issue.

I'm not working on any mongodb project right now but I've never had this issue before.

**Comment by moogway** [comment]
Yeah, I didn't mean it as an issue. It piqued my curiosity because the issue doesn't seem to appear on OS X environment. Furthermore, interesting was the fact that the driver didn't throw any errors, just stopped working.

So I thought I might discuss this. What would be a good place to ask if people faced this?

**Comment by Marsup** [comment]
On the driver itself more likely.

**Comment by moogway** [comment]
Thanks. Shall do that.
