### ISSUE TITLE
Question - Access named databases

### ISSUE THREAD

**Issue by danielo515** [Marsup/hapi-mongodb#27]
Hello,

I am wondering if there is any option to access the databases through name instead of array position.

I'm talking about this particular option:

> db : connection object to the database, if an array was provided for the configuration, it will be an array of connections in the same order

I would prefer to provide an object (or hashmap) of configurations and then be able to access them through database name.

Another question is, if I use the `decorate` option can I expect it to work the same way? I mean, I can access one of the DBs by `reques.server.mongo.db[1]` ?

**Comment by Marsup** [comment]
Actually reading the code I noticed I'm only using the decorate option if there's a single connection, using it on multiple ones would solve your problem I think. Want to contribute ?

**Comment by danielo515** [comment]
I have checked the code, and my understanding is that you decorate the `server` and the `request` with a single db or an array of DBs

https://github.com/Marsup/hapi-mongodb/blob/master/lib/index.js#L54-L59

So in theory, I can decorate multiple connections too. The only drawback is that they are positional values, not named

**Comment by danielo515** [comment]
According to mongodb documentation, the database object has a `databaseName` property

http://mongodb.github.io/node-mongodb-native/2.2/api/Db.html

What do you think about using it to map the dbs to a name? Maybe an extra `nameDbs` flag in the options object would be a good thing.

**Comment by Marsup** [comment]
I decided to fix the multiple decorations instead, in the unlikely but not impossible case that you connect to 2 different databases with the same name. You should be able to access it through `request.whateverdecorationyouwant.db`.

**Comment by Marsup** [comment]
Still do let me know if the solution is not enough but I think it solves your problem.

**Comment by danielo515** [comment]
Hello @Marsup ,

Thank you very much for implementing the fix. Could you briefly explain how it is supposed to work?

If I have an array of database connections, and I set decorate to `true`, how can I access each one? Reading the code I'm unable to understand how it works. My understanding says that each decoration overrides the previous one, so I'm a bit puzzled here.

Thanks and regards

**Comment by Marsup** [comment]
That's the thing, you don't set it to true, you set a string.

**Comment by danielo515** [comment]
Ok, that makes sense.
Is this version already released? If I just update the package can I start using it?

I don't know if you have considered this scenario, but currently what I'm doing is attaching a `decorate=true` to the array of options, so I can access `server.mongo.db[2]`. What will happen with the current version if I keep that? Will it work like before?

Regards

**Comment by Marsup** [comment]
Yes it's released, and no, doing this changes the way you access it, so it will only be accessible through the named properties. Why would you still need this kind of access ?

**Comment by danielo515** [comment]
I don't still need it, I was just curious about what will happen if someone tries to do the same that I did.

Thanks for it!
