### ISSUE TITLE
Error: Cannot start server before plugins finished registration

### ISSUE THREAD

**Issue by imtiazwazir** [Marsup/hapi-mongodb#28]
I am getting Error: Cannot start server before plugins finished registration

my code:

const Hapi = require('hapi');
var Boom = require("boom");

const dbOptions = {
  url: "mongodb://localhost:27017/comparekaro",
  settings: {
    db: {
      native_parser: false
    }
  }
}

const server = new Hapi.Server();

server.register({
    register: require('hapi-mongodb'),
    options: dbOptions
}, function (err) {
    if (err) {
        console.error(err);
        throw err;
    }
});

server.connection({
  port   : 3001,
  router : {
    stripTrailingSlash : true,
  },
  routes : {
    cors : true,
  }
});

server.route({
  method: 'GET',
  path: '/',
  handler: (request, reply) => {
    var db = request.server.plugins['hapi-mongodb'].db;
    var ObjectID = request.server.plugins['hapi-mongodb'].ObjectID;

    db.collection('catalogs').find((err, result) => {
      if (err) return reply(Boom.internal('Internal MongoDB error', err));
      reply(result);
    });
  }
});

server.route({
  method: 'GET',
  path: '/{name}',
  handler: (request, reply) => {
    reply(`i am ${request.params.name}`);
  }
});

server.start((err) => {
    if (err) {
        throw err;
    }
    console.log(`Server running at: ${server.info.uri}`);
});

**Comment by Marsup** [comment]
Updated the docs now that hapi changed its behavior, you have to move the start code after registrations as the error message says.
