### ISSUE TITLE
Options deprecation warning 

### ISSUE THREAD

**Issue by fbergr** [Marsup/hapi-mongodb#29]
I get following message when registering _hapi-mongodb_

```
...
server.register({
  register: require('hapi-mongodb'),
  options: dbOpts
}, function (err) {
...
```

```
the server/replset/mongos options are deprecated, all their options are supported at the top level of the options object [poolSize,ssl, ... ]
```

I am using:
- Hapi-MongoDB 6.2.0
- MongoDB 3.2.8
- Hapi 16.1.0
- Node.js 6.9.2
- Windows 7

**Comment by Marsup** [comment]
If you copied it from the readme, I just updated it, mongodb driver changed its options lately. For settings you should always refer to the driver's docs, I won't keep it up to date as I just pass it to the driver.
