### ISSUE TITLE
Always returning 404

### ISSUE THREAD

**Issue by quapaw** [Marsup/hapi-mongodb#30]
I am trying to utilize this plugin but always getting 404.

I can tell it is getting to the correct db.

Do you have a working demo that can be shared or have you seen this before.

Thanks

**************

Below is my configuration 
const dbOptions = {
    url: 'mongodb://localhost:27017/db',
    settings: {
        poolSize: 10
    },
    decorate: true
};

const manifest = {
    'connections': [
        {
            'port': 3000,
            'labels': ['api'],
            'host': 'localhost'
        }
    ],
    'registrations': [
        {
            'plugin': {
                'register': '.'
            },
            'plugin': {
                'register': 'hapi-mongodb',
                'options': dbOptions
                
            }
        }
    ]
};

Glue.compose(manifest, options, function(err, server) {
    server.start(function(err) {
        if(err) {
            throw err;
        }
        console.log('server running at: ' + server.info.uri);
        });
    });

`

**Comment by Marsup** [comment]
I don't see how a 404 status code, which is obviously http, can be related to this module in any way. And you didn't really provide a mean to reproduce your error.

**Comment by quapaw** [comment]
The issue is with plugin registration.
I am trying to utilize glue with hapi and register the database as a plugin vs in the actual server start.

When I do the code below and define hapi-mongodb as a plugin, it is not available in my route.
```
const manifest = {
    'connections': [
        {
            'port': 3000,
            'labels': ['api'],
            'host': 'localhost'
        }
    ],
    'registrations': [
        {
            'plugin': {
                'register': 'hapi-mongodb',
                'options': dbOptions
            },
            'plugin': {
                'register': '.',
                'dependencies': ['hapi-mongodb']
            }

        }
        ]
};


Glue.compose(manifest, options, function(err, server) {
    server.start(function(err) {
        if(err) {
            throw err;
        }
        console.log('server running at: ' + server.info.uri);
        });
    });

```

When I do this it is available in my route
```
const manifest = {
    'connections': [
        {
            'port': 3000,
            'labels': ['api'],
            'host': 'localhost'
        }
    ],
    'registrations': [
        {
            
            'plugin': {
                'register': '.',
                'dependencies': ['hapi-mongodb']
            }

        }
        ]
};

Glue.compose(manifest, options, function(err, server) {
    server.register({
                        register: require('hapi-mongodb'),
                        options: dbOptions
                    }, function (err) {
        if (err) {
            console.error(err);
            throw err;
        }
        server.start(function(err) {
            if(err) {
                throw err;
            }
            console.log('server running at: ' + server.info.uri);
            });
        });
});
```

I believe it is a load order issue.  But any help would be great

**Comment by Marsup** [comment]
Don't ignore glue errors, there might be one. It's still missing your routes and dbOptions for me to know exacty what you're doing. If possible, provide a *complete* example in a github repo.

**Comment by quapaw** [comment]
Not getting glue errors in the console
I did create a project to mirror what I am trying to do
https://github.com/quapaw/hapi-tut-monolith-04-customers

1. run npm install
2. run node localServer.js
3. hit http://localhost:3000/api/v1/customers/load
this will put three records in the mongodb test
4. http://localhost:3000/api/v1/customers/123

This all works
Stop localServer.js and start localServer2.js
And I get error back.

**Comment by Marsup** [comment]
That's not a problem with this plugin but with your glue manifest. The `registrations` array is a single object, also the `dependencies` is useless here as hapi will ignore it. Re-read glue and hapi's register documentations to double check you got it right.
