### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by jordymeow** [Marsup/hapi-mongodb#32]
Promises are now supported by the NodeJS core driver for mongodb. Is hapi-mongodb going to support promises too?

**Comment by Marsup** [comment]
Where specifically ? It only exposes the mongodb driver so support should be the same.

**Comment by jordymeow** [comment]
Sorry. It's what I actually thought. This plugin is a helper and it's simply the NodeJS driver behind it. I thought there was support for promises in the current NodeJS driver but apparently, there isn't. Not the fault of this plugin at all, it actually works perfectly.

**Comment by midnightcodr** [comment]
@jordymeow I am not sure what you meant by "I thought there was support for promises in the current NodeJS driver but apparently, there isn't" as promise is supported in the 2.x.x mongodb package. Nothing prevents you from using promises by using this plugin. The following code has been tested to work:

```javascript

const dbOpts = [{
    url: 'mongodb://localhost:27017/test',
    settings: {
        poolSize: 10
    },
    decorate: 'first'
}, {
    url: 'mongodb://localhost:27017/test',
    settings: {
        poolSize: 10
    },
    decorate: 'second'
}]
...
server.route( {
	method: 'GET',
	path: '/users/first',
	handler(request, reply) {
		const db = request.first.db;

		db.collection('users').findOne({}).then(result => {
			// console.log(result)
			reply(result)
		}).catch(err => {
			reply(Boom.internal('Internal MongoDB error', err));
		})
	}
});
```

**Comment by jordymeow** [comment]
@midnightcodr Yes, it seems to work with findOne but if I change it to find or to aggregate, then I get:

> db.collection(...).aggregate(...).then is not a function

I guess it's returning a cursor but if there are no promises with aggregate and find (I have tried this one too), I wonder what's the point to have it for findOne :) I am probably wrong somewhere but if you know how to get a promise from aggregate (or find) I would be so interested.

**Comment by midnightcodr** [comment]
@jordymeow , have you tried

```javascript
db.collection(...).find(...).toArray().then(items => {
    /* deal with items */
})
```

`aggregate` should also work by using the same pattern.

**Comment by jordymeow** [comment]
@midnightcodr Exactly what I was looking for, thank you, it's awesome!

**Comment by midnightcodr** [comment]
No problem @jordymeow, glad to help.
