### ISSUE TITLE
Creation of indexes

### ISSUE THREAD

**Issue by jordymeow** [Marsup/hapi-mongodb#36]
Hi,

First, thanks for this wonderful Hapi plugin. I would like to initialize indexes and maybe run various operations before the server is actually started (or right after it is started). How can I access the plugin/db after the server has been registered? The plugin is injected into the "server" variable in my routes, but I can't access it anywhere else (or before that). Would be perfect if I could use it before my server.start(). Is there a way?

**Comment by Marsup** [comment]
Sounds like a good use of hapi's `onPreStart`. You do have access to it on the server, depends how you registered it though, everything is in the readme.
