### ISSUE TITLE
method Hapi.Server() in README example should not be capitalized

### ISSUE THREAD

**Issue by benatkin** [Marsup/hapi-mongodb#37]
Hi, I noticed that the call to `Hapi.Server` in the README is capitalized, and that the README says it requires Hapi v17, and the Hapi example and API show the call as `Hapi.server()`.

**Comment by Marsup** [comment]
Both are valid, but I guess it doesn't hurt to stay consistent with hapi's docs.

**Comment by benatkin** [comment]
It's also more in line with JavaScript conventions. `Hapi.Server` is a function, rather than a class, but normally if it begins with a capital letter it's a class, and I suspect the lowercase version is so `Hapi.Server` could be changed to be the class in a later version.
